In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [6]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [10]:
np.eye(4)           

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.arange(1, 10, 2) 

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
arr = np.array([[[10, 20, 30], [40, 50, 60], [70, 80, 90]]])
print(arr)
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
Shape: (1, 3, 3)
Size: 9
Dimensions: 3
Data type: int32


In [14]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]], dtype='float32')

In [15]:
print(arr)
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
Shape: (3, 3)
Size: 9
Dimensions: 2
Data type: float32


In [16]:
n = arr.astype('float64')

In [17]:
n.dtype

dtype('float64')

In [18]:
arr.dtype

dtype('float32')

In [52]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

print(arr.dtype)
print(arr_int.dtype)

[1. 2. 3.]
[1 2 3]
float32
int32


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

(2, 3)


In [21]:
reshaped = arr.reshape((2, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [22]:
reshaped = arr.reshape((3, 2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6]
