In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [4]:
# Accessing an element
print(arr[1, 2])  # Row index 1, Column index 2 → Output: 6

6


In [5]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [6]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

'''Sheet 0:    [[ 1, 2, 3], [ 4, 5, 6]]
   Sheet 1:    [[ 7, 8, 9], [10, 11, 12]]'''
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [7]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6 0th row 1th column 2nd element
'''
[[1, 2, 3],
 [4, 5, 6]]  ← we're in this sheet
     ↑
     Row 1: [4, 5, 6]
                   ↑
           Index 2 → 6

'''

print(arr3D[:, 0, :])   # Get the first row from both sheets
'''
: → take all sheets (axis 0)

0 → take first row from each sheet (axis 1)

: → take all columns (axis 2)
    '''

6
[[1 2 3]
 [7 8 9]]


'\n: → take all sheets (axis 0)\n\n0 → take first row from each sheet (axis 1)\n\n: → take all columns (axis 2)\n    '

In [8]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [9]:
arr3D[:, 0, :] = 0

In [10]:
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]


In [11]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :] ## Output of arr3D.shape is → (depth, rows, columns)
print(first_rows)

[[0 0 0]
 [0 0 0]]


In [12]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
