In [2]:
# Python Zip Explained
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [3]:
# Using Python Lists
import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1, l2)]
end = time.time()
print(add[0:10])

print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.06899857521057129


In [4]:
# Using Numpy Arrays
import numpy as np
import time

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.014019012451171875


In [5]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(2, 3)

In [9]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


In [10]:
list1 = [1,2,3,4]
list_squares = [x ** 2 for x in list1]

In [11]:
list_squares

[1, 4, 9, 16]

In [12]:
arr1 = np.array([1, 2, 3, 4, 5])
numpy_aquares = arr1 ** 2
numpy_aquares

array([ 1,  4,  9, 16, 25])

In [13]:
# Create a NumPy array with values from 10 to 100
my_array = np.arange(10, 101)

# Print the shape of the array
print(my_array)
print("\nShape of the array:", my_array.shape)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]

Shape of the array: (91,)


In [14]:
import numpy as np
import time

# Create two large Python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# Create two large NumPy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Time multiplication of Python lists
start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
print(f"Time taken for Python lists: {end_time - start_time:.6f} seconds")

# Time multiplication of NumPy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken for NumPy arrays: {end_time - start_time:.6f} seconds")

Time taken for Python lists: 0.105019 seconds
Time taken for NumPy arrays: 0.000997 seconds


In [15]:
import numpy as np

# Create a NumPy array with 1 million elements
arr = np.arange(1000000)

# Get the size of a single item in bytes
item_size = arr.itemsize

# Get the total number of elements
num_elements = arr.size

# Calculate the total memory in bytes
total_memory_bytes = item_size * num_elements

# Convert to megabytes for a more readable format
total_memory_mb = total_memory_bytes / (1024 * 1024)

print(f"Size of each element: {item_size} bytes")
print(f"Total number of elements: {num_elements}")
print(f"Total memory size: {total_memory_bytes} bytes")
print(f"Total memory size: {total_memory_mb:.2f} MB")

Size of each element: 4 bytes
Total number of elements: 1000000
Total memory size: 4000000 bytes
Total memory size: 3.81 MB
