In [4]:
import numpy as np

In [6]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [16]:
sliced = arr[1:4]
sliced[0] = 999
print(sliced)
print(arr)  # [10 999 30 40 50]

[999  30  40]
[ 10 999  30  40  50]


In [36]:
a = arr[1:4].copy()

In [38]:
print(a)

[999  30  40]


In [40]:
a[0] = 1
print(a)

[ 1 30 40]


In [42]:
print(arr)

[ 10 999  30  40  50]


In [46]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [50]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr < 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[10 20]


### Exercises for Practice

- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats `[1.1, 2.2, 3.3]` into integers.
- Use fancy indexing to extract even numbers from `[1, 2, 3, 4, 5, 6]`.
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.


In [87]:
#1
arr = np.array([[1,2,3],[23,24,25],[32,33,34]])
print(arr)
print(arr.shape)

[[ 1  2  3]
 [23 24 25]
 [32 33 34]]
(3, 3)


In [97]:
#2
arr = np.array([[1.1, 2.2, 3.3]], dtype = 'int32')
print(arr)

[[1 2 3]]


In [104]:
#3
arr = np.array([1, 2, 3, 4, 5, 6])
idx = [1,3,5]
print(arr[idx])

[2 4 6]


In [127]:
#4
arr = np.array([1,2,3,4,5,6,7,8,9])
a = arr.reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [133]:
#5
arr = np.array([20,21,24,49,50,51,60,70,80,90,100])
print(arr[arr>50])

[ 51  60  70  80  90 100]
